[package]
name = "odl"
version = "0.1.0"
edition = "2024"
description = "wip"
repository = "https://github.com/jd1378/odl"
license = "MIT"

[dependencies]
reqwest = { version = "0.12.19", default-features = false, features = ["http2", "gzip", "brotli", "native-tls", "socks", "stream"] }
